controller_server:
  ros__parameters:
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.01
    min_y_velocity_threshold: 0.01
    min_theta_velocity_threshold: 0.01
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]
    odom_topic: /odometry/filtered

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.01
      movement_time_allowance: 10.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.25
      stateful: True

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      max_linear_vel: 3.0 
      min_linear_vel: -3.0
      max_angular_vel: 5.0
      min_angular_vel: -5.0
      max_linear_accel: 2.0
      max_linear_decel: -2.0
      max_angular_accel: 1.0
      max_angular_decel: -1.0
      lookahead_dist: 0.3
      min_lookahead_dist: 0.15
      max_lookahead_dist: 0.4
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 1.8
      use_velocity_scaled_lookahead_dist: true
      min_approach_linear_velocity: 0.1
      approach_velocity_scaling_dist: 1.0
      use_collision_detection: false # Disabled strictly for blind navigation
      max_allowed_time_to_collision_up_to_carrot: 1.0
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: false
      regulated_linear_scaling_min_radius: 0.1
      regulated_linear_scaling_min_speed: 0.1
      use_fixed_curvature_lookahead: false
      curvature_lookahead_dist: 2.0
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.5236
      interpolate_curvature_after_goal: false
      cost_scaling_dist: 0.3
      cost_scaling_gain: 1.0
      inflation_cost_scaling_factor: 2.0
      use_dynamic_window: false
      
      
local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: true
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.1
      robot_radius: 0.16
      plugins: ["inflation_layer"] # Removed obstacle_layer
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 4.0
        inflation_radius: 0.16
      always_send_full_costmap: True
